version: '3'
services:
  # nginx-proxy:
  #   image: jwilder/nginx-proxy
  #   command: ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  nginx:
    image: nginx
    volumes:
      # - ./nginx-sites.conf:/etc/nginx/sites-enabled/default:ro
      - railsocket:/tmp/
      - .:/myapp
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/logs:/var/log/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bash -c "bundle exec unicorn -c config/unicorn.rb -E development"
      # - bash -c "bundle exec rake routes"
      # - bash -c "bundle exec rake assets:precompile"
      # - "bash -c bundle exec rake db:setup"
    command: bash -c "bundle exec puma -C ./config/puma.rb config.ru"
    restart: unless-stopped
    volumes:
      - railsocket:/tmp/
    #   - .:/myapp
    ports:
      - "3000:3000"
    container_name: web
    depends_on:
      - postgres
    # networks:
    #   - default
    #   - webproxy
    environment: &environment
      - RAILS_ENV=production
      - DEFAULT_HOST=localhost
      - "VIRTUAL_PORT=80"
      - "VIRTUAL_PROTO=http"
      - VIRTUAL_HOST=m4rr.ru
      # - LETSENCRYPT_HOST=m4rr.ru
      # - LETSENCRYPT_EMAIL=remarr@gmail.com
      - SECRET_KEY_BASE=1e1f79bf016205045ffa0034fc35df4a41311af5c0d2066415e09859b3b4735dba8d3692f49e75a05c9f2b16fcd49d663fbfce2bd1a2400b950e49c2a8705885
      - RAILS_MASTER_KEY=28d69ab1e083cb8d07d098319191af56 # @dhh fuck off
  postgres:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

# networks:
#   default:
#     external:
#       name: webproxy

volumes:
  railsocket: