version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  # nginx:
  #   image: nginx
  #   # build: ./docker/web/
  #   labels:
  #     com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
  #   container_name: nginx-web
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-sites.conf:/etc/nginx/sites-enabled/default
  #     - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
  #     - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
  #     - /srv/volumes/nginx/html:/usr/share/nginx/html
  #     - /srv/volumes/nginx/certs:/etc/nginx/certs:ro
  # nginx-gen:
  #   image: jwilder/docker-gen
  #   command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
  #   container_name: nginx-gen
  #   restart: always
  #   volumes:
  #     - /srv/volumes/nginx/conf.d:/etc/nginx/conf.d
  #     - /srv/volumes/nginx/vhost.d:/etc/nginx/vhost.d
  #     - /srv/volumes/nginx/html:/usr/share/nginx/html
  #     - /srv/volumes/nginx/certs:/etc/nginx/certs:ro
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bundle exec unicorn -c config/unicorn.rb -E production
    restart: unless-stopped
    volumes:
      # - .:/myapp:rw
      - ./logs:/logs:rw
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment: &environment
      # - SQUIRTUAL_HOST=m4rr.ru
      - VIRTUAL_HOST=m4rr.ru
      # - LETSENCRYPT_HOST=m4rr.ru
      # - LETSENCRYPT_EMAIL=remarr@gmail.com
      - SECRET_KEY_BASE=rails_sucksd6de14662c9d81b7qcs90f07afdd59316e99c3591dbb092134dc4d613058f1b245524c598bae6876ee207fa41b3a7ab06714ffe76ffc3dd7d8b09

networks:
  default:
    external:
      name: webproxy
