version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: unless-stopped
    volumes:
      - .:/myapp
    ports:
      - "3000:80"
    depends_on:
      - db
    environment: &environment
      - SQUIRTUAL_HOST=m4rr.ru
      - VIRTUAL_HOST=m4rr.ru
      - LETSENCRYPT_HOST=m4rr.ru
      - LETSENCRYPT_EMAIL=remarr@gmail.com
